# -*- coding: utf-8 -*-
"""Gesture.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VW9lII22ozNkktbwpcsOjJ0qQlfVFVOf
"""

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout
from tensorflow.keras.preprocessing.image import ImageDataGenerator

# Parameters
IMG_SIZE = 64
BATCH_SIZE = 32
NUM_CLASSES = 7
DATASET_DIR = 'gesture_dataset'  # path to dataset

# These should be your gesture classes (match folder names in gesture_dataset)
gesture_labels = ['fine', 'ok', 'no', 'pointing', 'fist', 'stop', 'victory']

# Data Augmentation and Preprocessing
datagen = ImageDataGenerator(
    rescale=1./255,
    validation_split=0.2,
    rotation_range=20,
    zoom_range=0.2,
    horizontal_flip=True
)

train_gen = datagen.flow_from_directory(
    DATASET_DIR,
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    subset='training',
    shuffle=True
)

val_gen = datagen.flow_from_directory(
    DATASET_DIR,
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    subset='validation'
)

# Model Architecture
model = Sequential([
    Conv2D(32, (3,3), activation='relu', input_shape=(IMG_SIZE, IMG_SIZE, 3)),
    MaxPooling2D(2,2),

    Conv2D(64, (3,3), activation='relu'),
    MaxPooling2D(2,2),

    Conv2D(128, (3,3), activation='relu'),
    MaxPooling2D(2,2),

    Flatten(),
    Dense(128, activation='relu'),
    Dropout(0.5),
    Dense(NUM_CLASSES, activation='softmax')
])

# Compile Model
model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

# Train the Model
model.fit(
    train_gen,
    validation_data=val_gen,
    epochs=15
)

# Save the Model
model.save("gesture_model.h5")
print("Model trained and saved as gesture_model.h5")